webapp/news/models.py
from datetime import datetime
from webapp.db import db
from sqlalchemy.orm import relationship

class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    # соличество комментариев для новости
    def comments_count(self):
        return Comment.query.filter(Comment.news_id == self.id).count()

    def __repr__(self):
        return '<News {} {}'.format(self.title, self.url)

# миграция
# export FLASK_APP=webapp && flask db migrate -m "Comments model" - linux
# set FLASK_APP=webapp && flask db migrate -m "Comments model" - windows
# flask db upgrade
class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    news_id = db.Column(
        db.Integer,
        db.ForeignKey('news.id', ondelete='CASCADE'),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )
    # связи для удоброно обращения к моделям из другой модели
    news = relationship('News', backref='comments')
    user = relationship('User', backref='comments')

def __repr__(self):
    return '<Comment {}>'.format(self.id)

webapp/news/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.news.models import News
class CommentForm(FlaskForm):
    news_id = HiddenField('ID новости', validators=[DataRequired()])
    comment_text = StringField('Текст комментария', validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('отправить', render_kw={"class": "btn btn-primary"})

    def validate_news_id(self, news_id):
        if not News.query.get(news_id.data): # если новоси не существует
            raise ValidationError('Новости с таким id не существует')

webapp/news/views.py
from flask import abort, Blueprint, current_app, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required
from webapp.db import db

from webapp.news.forms import CommentForm # yнаша форма комментирования
from webapp.news.models import News, Comment
from webapp.weather import wether_by_city # импортировали свою функцию
from webapp.utils import get_redirect_target

blueprint = Blueprint('news', __name__)

@blueprint.route('/')
def index():
    title = 'Прогноз погоды'
    weather = wether_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    #news_list = News.query.order_by(News.published.desc()).all() # возврат всех новостей из бд c сортировкой по дате
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all() # фильтр по новостям у которых текст существует
    return render_template('news/index.html', page_title=title, weather=weather, news_list=news_list)

@blueprint.route('/news/<int:news_id>') # только число
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first() # нашли запись
    if not my_news: # если не нашли запись, то возвращаем 404
        abort(404)
    comment_form = CommentForm(news_id=my_news.id) # передаем в value id новости
    return render_template('news/single_news.html', page_title=my_news.title, news=my_news, comment_form=comment_form)

# обработчик формы комментирования
@blueprint.route('/news/comment', methods=['POST'])
@login_required # если кто-то пошлет данные на страницу, то будет идти проверка на авторизацию
def add_comment():
    #pass # напишем код потом, но при компиляции не получим ошибку - потому что функция не может быть пустой
    form = CommentForm()
    if form.validate_on_submit(): # если форма провалидирована
        comment = Comment(text=form.comment_text.data, news_id=form.news_id.data, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Комментарий успешно добавлен')
    else:
        for field, errors in form.errors.items(): # field - название поля, errors - список ошибок
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target()) # редиректим на туже страницу

webapp/templates/news/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8">
            {% include('messages.html') %}
            <h2>Новости</h2>
            {% for news in news_list %}
                <h3><a href="{{ url_for('news.single_news', news_id=news.id) }}">{{ news.title }}</a></h3>
                <p>{{ news.published.strftime('%d.%m.%Y') }} | Комментарии: {{ news.comments_count() }}</p>
                <hr>
            {% endfor %}
        </div>
        <div class="col-4">
            <h2>Прогноз погоды</h2>
                {% if weather %}
                    Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
                {% else %}
                    Сервис погоды временно недоступен
                {% endif %}
        </div>
    </div>
{%endblock %}

webapp/templates/news/single_news.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 news-content">
            {% include('messages.html') %}
            {{ news.text|safe }}
            {% if news.comments %}
                <h3>Комментарии:</h3>
                {% for comment in news.comments %}
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">{{ comment.text }}</h5>
                      <p class="card-text">
                          <small>Опубликовано: {{ comment.created.strftime('%d.%m.%Y') }}</small>
                          Автор: {{ comment.user.username }}
                      </p>
                    </div>
                  </div>
                {% endfor %}
            {% endif %}
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('news.add_comment') }}" method="POST">
                    {{ comment_form.hidden_tag() }}
                    <div class="form-group">
                        {{ comment_form.comment_text.label }}
                        {{ comment_form.comment_text() }}
                    </div>
                    {{ comment_form.submit() }}
                </form>
            {% else %}
                <p>
                    <a href="{{ url_for('user.login', next=request.full_path) }}">Авторизироваться</a> что бы добавить комментарий
                </p>
            {% endif %}
        </div>
        <div class="col-4">
            <h2>Другие новости</h2>

        </div>
    </div>
{%endblock %}