webapp/admin/views.py
from flask import Blueprint, render_template
#from flask_login import current_user, login_required
from webapp.user.decorators import admin_required # вызываем наш декоратор

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index(): # если проверка admin_required прошла, то он точно админ
    #return 'Привет админ'
    title = 'Админпанель'
    return render_template('admin/index.html', page_title=title)

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required # менеджер для всех логинов

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import get_redirect_target

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route("/login")
def login():
    if current_user.is_authenticated: # если залогинен, то страница логина ненужна
        return redirect(get_redirect_target()) # перенаправляем на то откуда пришел
    title = 'Авторизация'
    login_form = LoginForm() # создали экземпляр нашего класса
    return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit(): # валидируем данные
        user = User.query.filter(User.username == form.username.data).first() # сравниваем пользователей по имени
        if user and user.check_password(form.password.data): # если пользователь существует и проверка пароля прошла
            login_user(user, remember=form.remember_me.data) # логиним пользователя  запоминаем, remember - данные чекбокса с "запомнить меня"
            flash('Вы успешно вошли на сайт')
            return redirect(get_redirect_target()) # перенаправляем на то откуда пришел

    flash('Неправильные имя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route("/logout") # разлогиниваем пользователя
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('news.index')) # перенаправляем на главную

@blueprint.route("/register") # регистрация пользователя
def register():
    if current_user.is_authenticated: # если залогинен, то страница логина ненужна
        return redirect(url_for('news.index')) # перенаправляем на главную
    title = 'Регистрация'
    form = RegistrationForm() # создали экземпляр нашего класса
    return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route("/process-reg", methods=['POST']) # процесс регистрации
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно заегистрировались!')
        return redirect(url_for('user.login'))
    else: # вывод ошибок
        for field, errors in form.errors.items(): # field - название поля, errors - список ошибок
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" integrity="sha256-4xzi3YxNlqjrtSTUiSM+LSOfJoteCfbhpUnm1WDHvxk=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include "menu.html" %}
    <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %}{%endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
        <h1>{{ page_title }}</h1>
        <div class="row">
            <div class="col-8">
                <h2>Новости</h2>
                {% for news in news_list %}
                    <h3><a href="{{ news.url }}">{{ news.title }}</a></h3>
                    <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
                    <hr>
                {% endfor %}
            </div>
            <div class="col-4">
                <h2>Прогноз погоды</h2>
                    {% if weather %}
                        Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
                    {% else %}
                        Сервис погоды временно недоступен
                    {% endif %}
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Погода</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Главная <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
      </form>
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <span class="nav-link">Привет, {{ current_user.username }}</span>
        </li>
        {% if current_user.is_admin %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
          </li>
        {% else %}
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Логин</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

webapp/templates/messages.html
{% with messeges = get_flashed_messages() %}
    {% if messeges %}
        <div class="alert alert-warning" role="alert">
            {% for messege in messeges %}
                {{ messege }}<br />
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}